In [ ]:
# machine learning algorithm except numerical data
# LanguageText-Numerical Vector -natural language processing
# Images-numerical vector(features)-computer vision or image processing
# Audio 
# webinar on NLP
# text data-> representation- > ML technique-> output



In [ ]:
# what are the typical task to addressing with text data
#1. Sentiment Analysis-(CLassifcation problem -positive ,negative ,neutral)
# SPam email filtering (Classification problem -spam or not spam)
# Product feature extraction (regression problem -numerical value) entity extraction (classification problem -person name, location name, organization name)
# News Classification (classification problem -sports, politics, entertainment) predefined classes 
#text clustering


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
?CountVectorizer

Init signature:
CountVectorizer(
    *,
    input='content',
    encoding='utf-8',
    decode_error='strict',
    strip_accents=None,
    lowercase=True,
    preprocessor=None,
    tokenizer=None,
    stop_words=None,
    token_pattern='(?u)\\b\\w\\w+\\b',
    ngram_range=(1, 1),
    analyzer='word',
    max_df=1.0,
    min_df=1,
    max_features=None,
    vocabulary=None,
    binary=False,
    dtype=<class 'numpy.int64'>,
)
Docstring:     
Convert a collection of text documents to a matrix of token counts.

This implementation produces a sparse representation of the counts using
scipy.sparse.csr_matrix.

If you do not provide an a-priori dictionary and you do not use an analyzer
that does some kind of feature selection then the number of features will
be equal to the vocabulary size found by analyzing the data.

For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.

Read more in the :ref:`User Guide

In [47]:
corpus=[
  'This is the first document.',
  'This document is the second document.',
  'And this is the third one.',
  'Is this the first document?',
]
# transform the text data into numerical vector using CountVectorizer
vectorizer=CountVectorizer(lowercase=True)

In [48]:
# vectorizer.fit(corpus)
# learn
# Now it learn the vocabulary 

# learn and transform
X=vectorizer.fit_transform(corpus)

# 

In [49]:
X.shape

(4, 9)

In [50]:
vectorizer.get_feature_names_out()
# lexicographically sorted unique words in the corpus


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [51]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [52]:
import pandas as pd
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df

,and,document,first,is,one,second,the,third,this
0,0,1,1,1,0,0,1,0,1
1,0,2,0,1,0,1,1,0,1
2,1,0,0,1,1,0,1,1,1
3,0,1,1,1,0,0,1,0,1


In [53]:
# Each string in the corpus is represented with the words present by ignoring the word order , This representation is called as 'Bag of Words' representation.

# upper case and lower case are treated as same word by default in CountVectorizer. We can change this behaviour by setting the parameter lowercase=False while creating the CountVectorizer object.


In [57]:
# Experiment : INstantiate a Countvectorizer with "lowercase" =false and  observe the difference in the output.

# Important parameters of CountVectorizer
# lowercase : whether to convert all the characters in the text to lower case before tokenization.


vectorizer=CountVectorizer(lowercase=False)
X=vectorizer.fit_transform(corpus)
print(f"Number of feature: {len(vectorizer.get_feature_names_out())}")
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df


Number of feature: 11


,And,Is,This,document,first,is,one,second,the,third,this
0,0,0,1,1,1,1,0,0,1,0,0
1,0,0,1,2,0,1,0,1,1,0,0
2,1,0,0,0,0,1,1,0,1,1,1
3,0,1,0,1,1,0,0,0,1,0,1


In [54]:
# we need to puntuation marks to be removed from the text data before creating the bag of words representation. We can do this by setting the parameter "token_pattern" while creating the CountVectorizer object. By default, the token_pattern is set to r'(?u)\b\w\w+\b' which means that only words with 2 or more characters are considered as tokens and punctuation marks are ignored.
# token_pattern :r"(?u)\b\w\w+\b" is the default value for token_pattern parameter in CountVectorizer. It means that only words with 2 or more characters are considered as tokens and punctuation marks are ignored. We can change this behaviour by setting the token_pattern parameter to a different regular expression pattern.


In [ ]:
vectorizer=CountVectorizer(lowercase=True,token_pattern=r"[a-zA-Z.?]+")
X=vectorizer.fit_transform(corpus)
print(f"Number of feature: {len(vectorizer.get_feature_names_out())}")
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df
# Regular expression pattern r"[a-zA-Z.?]+" means that only words with 1 or more characters (both upper case and lower case) and punctuation marks (dot and question mark) are considered as tokens.


Number of feature: 11


,and,document,document.,document?,first,is,one.,second,the,third,this
0,0,0,1,0,1,1,0,0,1,0,1
1,0,1,1,0,0,1,0,1,1,0,1
2,1,0,0,0,0,1,1,0,1,1,1
3,0,0,0,1,1,1,0,0,1,0,1


In [66]:
# stop_words=['is','the','this']
# Remove the stop words  
vectorizer=CountVectorizer(
                        lowercase=True,
                        token_pattern=r"[a-zA-Z]+",
                        # stop_words='english')
                        stop_words=['is','the','this']
                        )
X=vectorizer.fit_transform(corpus)
print(f"Number of feature: {len(vectorizer.get_feature_names_out())}")
df=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df


Number of feature: 6


,and,document,first,one,second,third
0,0,1,1,0,0,0
1,0,2,0,0,1,0
2,1,0,0,1,0,1
3,0,1,1,0,0,0


Object `english` not found.
